# Generated by Django 2.2.4 on 2019-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=30)),
                ('stud_course', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'stud',
            },
        ),
    ]
